#!/bin/bash
# shellcheck disable=SC2034

# Path to store VM artifacts, defaults to .run in the same path as the script
# RUN_DIR="..."

# Number of VMs
NODE_COUNT=3

DISTRO=rancheros

# Version of RancherOS
RANCHEROS_VERSION=v1.5.2

NODE_CPUS=2
NODE_MEM=4096
NODE_HDDSIZE=16G

BRIDGE_DEV=bridge1
BRIDGE_IP=192.168.99.1/24

# What tap device to start with, eg. tap<N>, tap<N+1>, ...
TAP_DEV_INDEX=0
